services:
  # chroma:
  #   image: chromadb/chroma:1.0.20
  #   # ports:
  #   #   - "8000:8000"
  #   volumes:
  #     - chromadb:/data
  #   environment:
  #     IS_PERSISTENT: true
  #     ANONYMIZED_TELEMETRY: false
  postgres:
    image: postgres:alpine3.22
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5554:5554"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: -p 5554
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5554"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backends.yaml:/app/backends.yaml
    # - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "5556:5556"
    env_file:
      - .env
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backends.yaml:/app/backends.yaml
    # - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "5555:5555"
    env_file:
      - .env
volumes:
  chromadb:
  postgres_data:
